### ISSUE TITLE
Issue launching on 1.18

### ISSUE THREAD

**Issue by xXChick3nS0upXx** [Developer-Doge/Fox-Origin#10]
Every time I try to launch the mod, I get this error and I am not sure what to do about it Error: java.lang.RuntimeException: Could not execute entry point stage 'main' due to errors, provided by 'wiicustomorigins'!
Any help would be greatly appreciated

**Comment by TheOnlyTrueJedi** [comment]
I am also crashing when trying to launch the game with this mod, server and client are both crashing. I have all the latest up to date mods.
![image](https://user-images.githubusercontent.com/95608369/144800790-2f4c2ab0-110d-4142-9e93-c59b02e79251.png)

**Comment by BlueDDX** [comment]
Has this been resolved yet or still a work in progress?

**Comment by Developer-Doge** [comment]
> Has this been resolved yet or still a work in progress?

In the most recent commit (9 hours of the time of writing or 6 hours before your message) I fixed the issue. You can find the latest release in the github actions are (links can be found in the ReadMe of the repo) or on the curseforge page.
