### ISSUE TITLE
Foxling speed is canceled out by their smaller size.

### ISSUE THREAD

**Issue by flowersinthedaark** [Developer-Doge/Fox-Origin#11]
While messing around with friends we noticed that while Lepus' speed boost is noticeable, Foxling wasn't really any faster than origins with no speed boost. I don't know much on it but if I remember correctly Pehkui's scaling system also scales speed up and down with size, which could be connected to the issue?

**Comment by Developer-Doge** [comment]
I think I fixed this in the last update (but I will check), if you have any further issues I can fix it.
