### ISSUE TITLE
Differences between information about the mod, and in game

### ISSUE THREAD

**Issue by Broogus** [Developer-Doge/Fox-Origin#13]
The fox origin seems to be the same size as a normal player, Please give some sort of explanation please? In the description of the mod on the page it says foxes are shorter than players, but in game it doesn't.
![Pic](https://user-images.githubusercontent.com/87427267/162638048-79f63aee-d2ce-4987-927f-4061dbbcff67.PNG)

**Comment by Developer-Doge** [comment]
The fox origin is 0.8 times the size of a normal player. You can that it's in effect [here](https://github.com/Developer-Doge/Fox-Origin/blob/main/src/main/resources/data/wiicustomorigins/powers/bite_sized.json)
