### ISSUE TITLE
Missing lang

### ISSUE THREAD

**Issue by Ch1216** [Developer-Doge/Fox-Origin#14]
power.wiicustomorigins.boney.description is missing, assuming power.wiicustomorigins.boney.name is missing too
power.wiicustomorigins.undead.description is missing
power.wiicustomorigins.no_sleep.description is missing assuming power.wiicustomorigins.no_sleep.name is missing too

**Comment by Developer-Doge** [comment]
Yeah, that is cause the Boneling origin is in beta (not meant to be used in production), I can add the lang to the mod once I update to 1.20.
