### ISSUE TITLE
Trade Prevention Foxling Origin

### ISSUE THREAD

**Issue by lebes04** [Developer-Doge/Fox-Origin#15]
Trade prevention on the Fox origin is as of this moment not working on the 1.18.1 version. 
I have tried a couple of things, including removing all mods except those that are necessary for the mod, so that means just Pekhui, Origins, this mod and the Fabric API remaining in the mods folder.
I have also tried to run it with the extraOrigins mod, but it did not make a difference.

**Comment by Developer-Doge** [comment]
Yeah, I honestly have no idea what was wrong with it at the time but it appears to be working on my end using the newest 1.19.4 version.
